DROP TABLE IF EXISTS BOOK CASCADE;
DROP TABLE IF EXISTS AUTHOR CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS COMMENT CASCADE;

CREATE TABLE AUTHOR
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE GENRE
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE BOOK
(
    ID           BIGINT PRIMARY KEY,
    NAME         VARCHAR(255),
    PUBLISH_DATE VARCHAR(255),
    AUTHOR_ID    BIGINT REFERENCES AUTHOR (ID),
    GENRE_ID     BIGINT REFERENCES GENRE (ID)
);

CREATE TABLE COMMENT
(
    ID        BIGINT PRIMARY KEY,
    BOOK_ID   BIGINT REFERENCES BOOK (ID) ON DELETE CASCADE,
    USER_NAME VARCHAR(255),
    TEXT      VARCHAR(255)
);