version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    ports:
      - 8080:8080
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
    restart: always